{
 "title": "京东云路由器面板",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "运行时长",
   "type": "stat",
   "description": "开机时长",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "JD{jdwifi_status=\"up_time\"}"
    }
   ]
  },
  {
   "title": "累计上传流量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "JD{jdwifi_status=\"route_upload\"}"
    }
   ]
  },
  {
   "title": "累计下载流量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "JD{jdwifi_status=\"route_download\"}"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "yaxes": [
    { "format": "KiBs" }
   ],
   "targets": [
    {
     "expr": "irate(JD{jdwifi_status=\"route_download_speed\"}[5m])*8",
     "legendFormat": "下行"
    },
    {
     "expr": "irate(JD{jdwifi_status=\"route_upload_speed\"}[5m])*8",
     "legendFormat": "上传"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "JD{jdwifi_status=\"cpu_load\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "JD{jdwifi_status=\"mem_load\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "设备连接列表",
   "type": "table-old",
   "description": "设备名称：可在路由器后台更改\n\n连接协议：2.4G/5G （无线）wire（有线）",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(1, sort_desc(JDclient{})) by (device_ip, device_uid)",
     "legendFormat": "设备IP"
    },
    {
     "expr": "max(rate(JDclient{des=\"device_download_speed\"}[5m])*8) by (device_ip)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(JDclient{des=\"device_upload_speed\"}[5m])*8) by (device_ip)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "历史网络流量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "yaxes": [
    { "format": "KiBs" }
   ],
   "targets": [
    {
     "expr": "max(rate(JDclient{des=\"device_download_speed\"}[5m])*8) by (device_ip)",
     "legendFormat": "{{device_ip}} 下行"
    },
    {
     "expr": "max(rate(JDclient{des=\"device_upload_speed\"}[5m])*8) by (device_ip)",
     "legendFormat": "{{device_ip}} 上传"
    }
   ]
  }
 ]
}