apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-builder
  labels:
    app: github-actions-builder
spec:
  replicas: 10
  selector:
    matchLabels:
      app: github-actions-builder
  template:
    metadata:
      labels:
        app: github-actions-builder
    spec:
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
      containers:
        - name: github-actions-builder
          imagePullPolicy: Always
          image: 'registry.ap-northeast-1.aliyuncs.com/bohai_repo/github-runner:2.304.0'
          env:
            - name: GITHUB_OWNER
              value: "yaobohai"
            - name: GITHUB_REPOSITORY
              value: "builder"
            - name: GITHUB_TOKEN
              value: "xxxxxxx"
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-sock
              readOnly: false