apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: 5
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
        - name: github-runner
          imagePullPolicy: Always
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/
          image: 'registry.ap-northeast-1.aliyuncs.com/bohai_repo/github-runner-arm64:2.304.0'
          env:
            - name: REGIST_TYPE
              value: "personal"
            - name: GITHUB_OWNER
              value: "bohai-repo"
            - name: GITHUB_REPOSITORY
              value: "builder"
            - name: RUNNER_LABELS
              value: "kubernetes-arm64"
            - name: GITHUB_PAT
              value: "xxxxxxx"
        - name: docker-build
          image: 'docker:24.0.5-dind'
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/run/
              name: docker-socket
      volumes:
      - name: docker-socket
        emptyDir: {}