# 默认配置常量
DEFAULT_TIMEOUT = 5
DEFAULT_SSE_READ_TIMEOUT = 60 * 5  # 5分钟
MAX_TIMEOUT_MINUTES = 15
TIMEOUT_MULTIPLIER = 60

HEADER_COOKIE = "Cookie"
HEADER_TIMEOUT = "Timeout"
HEADER_SERVER_KEYS = "X-Server-Keys"
