user  root;
worker_processes  auto;

pid        /etc/nginx/logs/nginx.pid;

events {
    worker_connections  102400;
}

http {
    include       /etc/nginx/conf/mime.types;
    default_type  application/octet-stream;
    #隐藏版本号
    server_tokens off;
    client_max_body_size 100m;
    underscores_in_headers on;
    sendfile        on;
    keepalive_timeout  120;
    # 关闭日志
    access_log off;
    error_log off;
    server {
        listen 443 ssl http2;
        server_name v2ray_domain;
        root /etc/nginx/html;
        index index.php index.html;
        ssl_certificate /etc/nginx/ssl/ssl.cer;
        ssl_certificate_key /etc/nginx/ssl/ssl.key;
        ssl_protocols   TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers     'TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:TLS13-AES-128-CCM-8-SHA256:TLS13-AES-128-CCM-SHA256:EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+ECDSA+AES128:EECDH+aRSA+AES128:RSA+AES128:EECDH+ECDSA+AES256:EECDH+aRSA+AES256:RSA+AES256:EECDH+ECDSA+3DES:EECDH+aRSA+3DES:RSA+3DES:!MD5';
        ssl_prefer_server_ciphers   on;
        ssl_early_data  on;
        ssl_stapling on;
        ssl_stapling_verify on;
        location /v2ray_path {
            proxy_redirect off;
            proxy_pass http://127.0.0.1:11234;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
    include /etc/nginx/conf.d/*.conf;
}
