user  root;
worker_processes  auto;
pid       /app/nginx/nginx.pid;
events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  120;
    client_max_body_size 102400m;

    server {
        listen       80;
        server_name  127.0.0.1;

        index index.html;
        root /app/web/;

        location /files/ {
            root /app/remote-download-service/;
        }

        location /api/ {
            proxy_pass http://localhost:8080/;
        }
        access_log  /app/remote-download-service/logs/access.log;
        error_log   /app/remote-download-service/logs/error.log;
    }
}